# Generated by Django 4.1.4 on 2022-12-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=400, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('play_store_url', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('app_store_url', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_url', models.CharField(blank=True, max_length=600, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('google_auth_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.user')),
            ],
        ),
        migrations.CreateModel(
            name='WatchConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=100)),
                ('google_fit_refresh_token', models.CharField(blank=True, max_length=100, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.userapp')),
            ],
        ),
    ]
