# Generated by Django 4.1.4 on 2022-12-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0002_alter_userapp_google_auth_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchconnection',
            name='google_fit_refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
