# Generated by Django 4.1.4 on 2022-12-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0004_fitnessdata_created_at_fitnessdata_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdata',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.watchconnection'),
        ),
    ]
