# Generated by Django 4.1.4 on 2022-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0005_fitnessdata_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchconnection',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
