# Generated by Django 4.1.4 on 2022-12-15 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0006_watchconnection_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdata',
            name='record_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='record_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
