# Generated by Django 4.1.4 on 2022-12-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0007_fitnessdata_record_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdata',
            name='data_source',
            field=models.CharField(blank=True, choices=[('google_fit', 'google_fit'), ('api', 'api')], max_length=100, null=True),
        ),
    ]
