# Generated by Django 4.1.4 on 2022-12-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0008_fitnessdata_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchconnection',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
