# Generated by Django 4.1.4 on 2023-01-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0009_watchconnection_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdata',
            name='data_source',
            field=models.CharField(blank=True, choices=[('google_fit', 'google_fit'), ('api', 'api'), ('sdk_healthkit', 'sdk_healthkit')], max_length=100, null=True),
        ),
    ]
