# Generated by Django 4.1.4 on 2023-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0010_alter_fitnessdata_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='payment_plan',
            field=models.CharField(blank=True, choices=[('free', 'free'), ('startup', 'startup'), ('enterprise', 'enterprise')], max_length=100, null=True),
        ),
    ]
