# Generated by Django 4.1.4 on 2023-01-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0013_testwebhookdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchconnection',
            name='google_fit_email',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
