# Generated by Django 4.1.4 on 2023-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0014_watchconnection_google_fit_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='payment_plan',
            field=models.CharField(choices=[('free', 'free'), ('startup', 'startup'), ('business', 'business'), ('enterprise', 'enterprise')], default='free', max_length=100),
        ),
    ]
