# Generated by Django 4.1.4 on 2023-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0015_alter_userapp_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchconnection',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
