# Generated by Django 4.1.4 on 2023-02-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0016_watchconnection_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnabledPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_app_id', models.CharField(max_length=200)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectedPlatformMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('logged_in', models.BooleanField(default=True)),
                ('last_modified_for_data_types', models.JSONField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userapp',
            name='enabled_platforms',
            field=models.ManyToManyField(blank=True, to='watch_sdk.enabledplatform'),
        ),
        migrations.AddField(
            model_name='watchconnection',
            name='connected_platforms',
            field=models.ManyToManyField(blank=True, to='watch_sdk.connectedplatformmetadata'),
        ),
    ]
