# Generated by Django 4.1.4 on 2023-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0017_platform_enabledplatform_connectedplatformmetadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enabledplatform',
            name='platform_app_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
