# Generated by Django 4.1.4 on 2023-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0021_remove_userapp_google_auth_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='enabled_platforms',
            field=models.ManyToManyField(blank=True, to='watch_sdk.enabledplatform'),
        ),
    ]
