# Generated by Django 4.1.4 on 2023-02-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0022_alter_userapp_enabled_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchconnection',
            name='logged_in',
        ),
        migrations.RemoveField(
            model_name='watchconnection',
            name='platform',
        ),
    ]
