# Generated by Django 4.1.4 on 2023-02-11 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0023_remove_watchconnection_logged_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedplatformmetadata',
            name='connected_device_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
