# Generated by Django 4.1.4 on 2023-02-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0025_datatype_userapp_enabled_data_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
