# Generated by Django 4.1.4 on 2023-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0026_alter_datatype_name_alter_platform_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabledplatform',
            name='platform_app_secret',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
