# Generated by Django 4.1.4 on 2023-02-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0027_enabledplatform_platform_app_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessData',
        ),
    ]
