# Generated by Django 4.1.4 on 2023-02-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0028_delete_fitnessdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('owner_id', models.CharField(max_length=100)),
                ('owner_type', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
