# Generated by Django 4.1.4 on 2023-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0029_fitbitnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedplatformmetadata',
            name='platform_connection_uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
