# Generated by Django 4.1.4 on 2023-02-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0030_connectedplatformmetadata_platform_connection_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='enabled_platforms',
        ),
        migrations.AddField(
            model_name='enabledplatform',
            name='user_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.userapp'),
            preserve_default=False,
        ),
    ]
