# Generated by Django 4.1.4 on 2023-03-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0031_remove_userapp_enabled_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedplatformmetadata',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.watchconnection'),
        ),
    ]
