# Generated by Django 4.1.4 on 2023-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0033_remove_watchconnection_connected_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabledplatform',
            name='webhook_verify_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
