# Generated by Django 4.1.4 on 2023-03-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0034_enabledplatform_webhook_verify_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabledplatform',
            name='webhook_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
