# Generated by Django 4.1.4 on 2023-03-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0035_enabledplatform_webhook_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100)),
                ('aspect_type', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('updates', models.JSONField()),
                ('connected_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.connectedplatformmetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
