# Generated by Django 4.1.4 on 2023-03-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0036_stravawebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSDataHashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=100)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.watchconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
