# Generated by Django 4.1.4 on 2023-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0038_debugwebhooklogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabledplatform',
            name='sync_manual_entries',
            field=models.BooleanField(default=False),
        ),
    ]
