# Generated by Django 4.1.4 on 2023-04-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0039_enabledplatform_sync_manual_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaWebhookSubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.userapp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
