# Generated by Django 4.1.4 on 2023-04-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0040_stravawebhooksubscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='debug_store_webhook_logs',
            field=models.BooleanField(default=False),
        ),
    ]
