# Generated by Django 4.1.4 on 2023-04-04 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0042_debugiosdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='tech_stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
