# Generated by Django 4.1.4 on 2023-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0043_userapp_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='access_users',
            field=models.ManyToManyField(blank=True, related_name='access_users', to='watch_sdk.user'),
        ),
    ]
