# Generated by Django 4.1.4 on 2023-04-07 09:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0044_userapp_access_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabledplatform',
            name='enabled_scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
