# Generated by Django 4.1.4 on 2023-04-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0045_enabledplatform_enabled_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnprocessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.watchconnection')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
