# Generated by Django 4.1.4 on 2023-04-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0046_unprocesseddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.userapp')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
