# Generated by Django 4.1.4 on 2023-05-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0048_datasyncmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasyncmetric',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.platform'),
        ),
    ]
