# Generated by Django 4.1.4 on 2023-05-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0049_datasyncmetric_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.userapp')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.watchconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
