# Generated by Django 4.1.4 on 2023-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0050_useractivitymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedplatformmetadata',
            name='gfit_access',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedplatformmetadata',
            name='gfit_access_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
