# Generated by Django 4.1.4 on 2023-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0051_connectedplatformmetadata_gfit_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedplatformmetadata',
            name='gfit_access',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
