# Generated by Django 4.1.4 on 2023-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0052_alter_connectedplatformmetadata_gfit_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='data_storage_option',
            field=models.CharField(choices=[('allow', 'allow'), ('deny', 'deny'), ('both', 'both')], default='deny', max_length=100),
        ),
    ]
