# Generated by Django 4.1.4 on 2023-06-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0052_alter_connectedplatformmetadata_gfit_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('manual_entry', models.BooleanField(default=False)),
                ('device', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra_data', models.JSONField()),
                ('connected_platform_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.connectedplatformmetadata')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='watch_sdk.datatype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
