# Generated by Django 4.1.4 on 2023-10-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_sdk', '0053_userapp_data_storage_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('manual_entry', models.BooleanField(default=False)),
                ('value', models.FloatField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('source_device', models.CharField(blank=True, max_length=200, null=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.datatype')),
                ('source_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.platform')),
                ('user_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_sdk.watchconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
