version: '1'

services:
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: heka-api
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
