version: '1'

services:
  nginx:
    container_name: heka-nginx
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - api
  api:
    container_name: heka-api
    build: .
    restart: always
    env_file:
      - .env
    command: daphne --bind 0.0.0.0 --port 5000 core.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/static

volumes:
  static_volume:
