# Generated by Django 4.1.4 on 2022-12-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishQualitativeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_melotonin', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishQuantitativeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiloCalories', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('vitaminA', models.FloatField(blank=True, null=True)),
                ('vitaminC', models.FloatField(blank=True, null=True)),
                ('vitaminD', models.FloatField(blank=True, null=True)),
                ('vitaminE', models.FloatField(blank=True, null=True)),
                ('vitaminK', models.FloatField(blank=True, null=True)),
                ('thiamin', models.FloatField(blank=True, null=True)),
                ('riboflavin', models.FloatField(blank=True, null=True)),
                ('niacin', models.FloatField(blank=True, null=True)),
                ('vitaminB6', models.FloatField(blank=True, null=True)),
                ('folate', models.FloatField(blank=True, null=True)),
                ('vitaminB12', models.FloatField(blank=True, null=True)),
                ('vitaminB5', models.FloatField(blank=True, null=True)),
                ('vitaminB9', models.FloatField(blank=True, null=True)),
                ('choline', models.FloatField(blank=True, null=True)),
                ('magnesium', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('zinc', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro', models.CharField(blank=True, max_length=1000, null=True)),
                ('steps', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_db.ingredientitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='diet_db.ingredient')),
                ('qualitative_nutrition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_db.dishqualitativenutrition')),
                ('quantitative_nutrition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_db.dishquantitativenutrition')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_db.recipe')),
                ('tags', models.ManyToManyField(blank=True, to='diet_db.dishtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
